ALTER TABLE Pacientes
ADD DNI VARCHAR(20) NULL;
GO

UPDATE Pacientes
SET DNI = CAST((RAND(ID_Paciente) * 10000000 + 30000000) AS INT)
WHERE DNI IS NULL;
GO

ALTER TABLE Pacientes
ALTER COLUMN DNI VARCHAR(20) NOT NULL;
GO